// Export all screen components for easier importing
export { default as LoginScreen } from "./LoginScreen";
export { default as RegisterScreen } from "./RegisterScreen";
export { default as HabitsScreen } from "./HabitsScreen";
export { default as FeedScreen } from "./FeedScreen";
export { default as FriendsScreen } from "./FriendsScreen";
export { default as TodayScreen } from "./TodayScreen";
export { default as GalleryScreen } from "./GalleryScreen";
export { default as ProfileScreen } from "./ProfileScreen";
export { default as CreateHabitScreen } from "./CreateHabitScreen";
export { default as HabitDetailScreen } from "./HabitDetailScreen";
export { default as CameraScreen } from "./CameraScreen";
export { default as LoadingScreen } from "./LoadingScreen";
export { default as SettingsScreen } from "./SettingsScreen";
